language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script: coverage run --source paramcomparison test.py

after_success:
  coveralls
